name: Java CI

on: [push]

jobs:
  jar-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

  docker-push:
    needs: jar-build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download target
        uses: actions/download-artifact@v2
        with:
          name: target-files
          path: target

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag hollandr/queerfy-backend

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: hollandr/queerfy-backend